version: '3.8'
services:

  elasticsearch-haystack:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  kibana-haystack:
    image: docker.elastic.co/kibana/kibana:8.17.0
    networks: 
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-haystack:9200
    ports:
      - 5609:5601
networks:
    elastic:
        driver: bridge
